### ISSUE TITLE
Not switching to hdmi when Docked

### ISSUE THREAD

**Issue by Jx2ofB** [henryjfry/batocera_gpi2#1]
Thank you so much for your work on this!!! I copied the 3 txt files to the root of my card and ran the wget. I have the cm4 no storage and retroflag GPi Case 2. Thank you again!

**Comment by henryjfry** [comment]
Just curious, did you find this from another Batocera github issue?

If so can you link it in a comment that way it'll maybe help more people or maybe get directly integrated into future versions.

Cheers

**Comment by Jx2ofB** [comment]
Solution was just dock it before powering it up and to be patient. I discovered your solution from google that led straight to your GitHub. Let me know where you want me to post that this works.

**Comment by henryjfry** [comment]
No thats cool, I was just curious as it appears to have been an issue for a while but clearly hasn't received a lot of attention so i didnt really expect to have been the primary source.

FYI if you are running my python script it should change over the boot files on dock/undock. Therefore you can dock it, and then switch it off/back on and it will startup in the HDMI mode.
Or conversely undock it and turn it off and on and itll start in LCD mode.

It takes a good 10-15s in the boot process before it can determine if its docked correctly so its quicker if you let it decide while its switched on and then power cycle.

But just a note if you are doing this you may need a small tweak to change the sound.  I cant remember if this is 100% necessary or not but i think on boot it sets the HDMI and reboots, the dock/undock may not so you may want to add a line which always sets the sound to match the current booting config.
